class ConfigurationError(RuntimeError): ...
class OperationError(RuntimeError): ...
class StaleProposalError(RuntimeError): ...
class PolicyError(RuntimeError): ...

class NativeProposal:
    def report(self) -> str: ...
    def apply(self, allow_partial: bool = False) -> str: ...

def discover_json(root: str) -> str: ...
def prepare(root: str, targets: list[str], options: str) -> NativeProposal: ...
def scan_json(root: str, targets: list[str], options: str) -> str: ...
def doctor_json(root: str, options: str) -> str: ...
def init_json(
    root: str, targets: list[str], options: str, fetch_tools: bool
) -> str: ...
def recover_json(root: str) -> str: ...
def cli(args: list[str]) -> int: ...
