[package]
name = "depsmith-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
depsmith-core = { path = "../core" }
serde_json.workspace = true
pyo3 = { version = "0.29", features = ["abi3-py310"] }
depsmith-cli = { path = "../cli" }

[lints]
workspace = true
