"""Generate the wiki's CLI and Python API reference pages from the installed package.

Usage: python scripts/gen-reference.py [--check]

The pages are derived only from `depsmith --help` output and the public API's
docstrings, so they never need editing by hand. With --check, exit 1 when the
committed pages differ from what would be generated, or when an internal
wiki link points to a missing page.
"""

import dataclasses
import inspect
import re
import subprocess
import sys
from pathlib import Path

import depsmith

WIKI = Path(__file__).resolve().parent.parent / "docs" / "wiki"
HEADER = (
    "<!-- Generated by scripts/gen-reference.py from {source}; do not edit. -->\n\n"
)
COMMANDS = ["discover", "doctor", "check", "update", "scan", "recover"]
FUNCTIONS = ["discover", "prepare", "scan", "doctor", "recover"]


def cli_help(*args: str) -> str:
    result = subprocess.run(
        [sys.executable, "-m", "depsmith", *args, "--help"],
        capture_output=True,
        text=True,
        check=True,
        env={"PATH": "", "NO_COLOR": "1", "COLUMNS": "100"},
    )
    return "\n".join(line.rstrip() for line in result.stdout.strip().splitlines())


def cli_reference() -> str:
    parts = [
        HEADER.format(source="`depsmith --help`"),
        "# CLI reference\n\n",
        "Every option is global: it may be given before or after the command.\n",
        "Exit statuses: 0 success or nothing pending, 1 updates pending (`check`),\n",
        "2 invalid request, 3 tool or scanner failure, 4 policy rejection,\n",
        "5 partial success, 130 interrupted.\n\n",
        "## depsmith\n\n```text\n",
        cli_help(),
        "\n```\n",
    ]
    for command in COMMANDS:
        parts += [f"\n## depsmith {command}\n\n```text\n", cli_help(command), "\n```\n"]
    return "".join(parts)


def public_members() -> tuple[list[object], list[type], list[type]]:
    functions = [getattr(depsmith, name) for name in FUNCTIONS]
    classes, errors = [], []
    for name in sorted(vars(depsmith)):
        value = getattr(depsmith, name)
        if name.startswith("_") or not inspect.isclass(value):
            continue
        if not value.__module__.startswith("depsmith"):
            continue
        (errors if issubclass(value, Exception) else classes).append(value)
    return functions, classes, errors


def signature(obj: object) -> str:
    text = str(inspect.signature(obj))
    # Postponed annotations are strings; unquote them but keep quoted defaults.
    return re.sub(r"(: |-> )'([^']*)'", r"\1\2", text).replace("depsmith.", "")


SECTIONS = {"Args", "Attributes", "Returns", "Raises", "Example", "Examples"}


def inline(text: str) -> str:
    """Convert reStructuredText inline markup used in docstrings to Markdown."""
    text = re.sub(r":(?:class|func|meth|attr):`~?([^`]+)`", r"`\1`", text)
    return re.sub(r"``([^`]+)``", r"`\1`", text)


def markdown(doc: str) -> str:
    """Render a Google-style docstring as Markdown."""
    out, lines, i = [], doc.splitlines(), 0
    while i < len(lines):
        header = lines[i].rstrip(":")
        if lines[i].endswith(":") and header in SECTIONS:
            block = []
            i += 1
            while i < len(lines) and (not lines[i] or lines[i].startswith(" ")):
                block.append(lines[i][4:])
                i += 1
            while block and not block[-1]:
                block.pop()
            out.append(f"**{header}**\n")
            if header.startswith("Example"):
                out += ["```python", *block, "```"]
            else:
                entries = []
                for line in block:
                    if line.startswith(" ") and entries:
                        entries[-1] += " " + line.strip()
                    elif line.strip():
                        entries.append(line.strip())
                for entry in entries:
                    name, sep, text = entry.partition(": ")
                    if sep and " " not in name:
                        out.append(f"- `{name}`: {inline(text)}")
                    else:
                        out.append(f"- {inline(entry)}")
            out.append("")
            continue
        out.append(inline(lines[i]))
        i += 1
    return "\n".join(out).strip()


def section(title: str, obj: object) -> str:
    doc = markdown(inspect.getdoc(obj) or "")
    return f"### `{title}`\n\n{doc}\n\n"


def class_section(cls: type) -> str:
    if dataclasses.is_dataclass(cls):
        fields = ", ".join(f"{f.name}: {f.type}" for f in dataclasses.fields(cls))
        return section(f"{cls.__name__}({fields})", cls)
    return section(cls.__name__, cls)


def python_reference() -> str:
    functions, classes, errors = public_members()
    parts = [
        HEADER.format(source="the `depsmith` package docstrings"),
        "# Python API reference\n\n",
        markdown(inspect.getdoc(depsmith)) + "\n\n",
        "## Functions\n\n",
    ]
    parts += [section(f"{f.__name__}{signature(f)}", f) for f in functions]
    parts.append("## Classes\n\n")
    for cls in classes:
        parts.append(class_section(cls))
        for name, member in vars(cls).items():
            if not name.startswith("_") and inspect.isfunction(member):
                parts.append(
                    section(f"{cls.__name__}.{name}{signature(member)}", member)
                )
    parts.append("## Exceptions\n\n")
    parts += [section(e.__name__, e) for e in errors]
    return "".join(parts).rstrip() + "\n"


def broken_links() -> list[str]:
    """Internal wiki links (``[text](Page-Name)``) whose page does not exist."""
    pages = {path.stem for path in WIKI.glob("*.md")}
    broken = []
    for path in sorted(WIKI.glob("*.md")):
        for target in re.findall(
            r"\]\(([A-Za-z0-9_-]+)(?:#[^)]*)?\)", path.read_text()
        ):
            if target not in pages:
                broken.append(f"{path.name}: {target}")
    return broken


def main() -> int:
    pages = {
        WIKI / "CLI-reference.md": cli_reference(),
        WIKI / "Python-API.md": python_reference(),
    }
    check = "--check" in sys.argv[1:]
    stale = []
    for path, content in pages.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(path.name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    links = broken_links()
    for link in links:
        print(f"Broken wiki link: {link}", file=sys.stderr)
    if stale:
        print(
            f"Stale generated pages: {', '.join(stale)}; run python scripts/gen-reference.py",
            file=sys.stderr,
        )
        return 1
    return 1 if links else 0


if __name__ == "__main__":
    raise SystemExit(main())
